<<<<<<< HEAD

title: 초보개발자 찬우
subtitle: hello
email: niuse1235@gmail.com
description: c++ 언어 기반 클라이언트 개발 지망생   # this means to ignore newlines until "baseurl:"

  
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "niuse1235." 
github_username: niuse1235

Page:

- 컴퓨터 공학과 2018108253 김찬우 입니다.
- 오픈소스 개발 방법론을 수강하며 오픈소스 라이센스를 배워가는 초보 코딩 프로그래머 입니다.

# 
- Github ID:niuse1235
- Github :https://github.com/niuse1235
- E-mail :niuse1235@gmail.com

# 사용언어
- C
- C++
- JAVA
- Python

# 학력
- 오현고등학교 졸업
- 제주대학교 컴퓨터 공학과 재학


# 관심분야

- 클라이언트 개발을 목표로 하고 있습니다.
- 언어로는 C++를 기반으로 사용하여 언리얼을 통한 클라이언트 개발입니다.
- 

 


=======
title: 초보개발자 지망생 찬우
email: niuse1235@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://niuse1235.github.io" 
twitter_username: jekyllrb
github_username:  jekyll
>>>>>>> 12ee1309f4c4dc35d136796eaf86ff7c74d2d31a

# Build settings
#theme: jekyll-theme-clean-blog
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

plugins:
  - jekyll-feed
  - jekyll-remote-theme


